### ISSUE TITLE
Add Loading System

### ISSUE THREAD

**Issue by Aquarelix** [Aventero/MagicalMushrooms#24]
## Idea
The user can save and should now be able to load the saved data.
Loading should be possible on the main menu.

## To-Do
- [x] Load the save when the user hits the "Continue" button
- [x] Loading the player and witch position
- [x] Load the coins
- [x] Load the latest Checkpoint
