### ISSUE TITLE
Activate CoinVaccum by holding the right mouse button

### ISSUE THREAD

**Issue by Aquarelix** [Aventero/MagicalMushrooms#25]
## Idea
The CoinVaccum is no longer a skill for the player and therefore, its own thing.

## To-Do
- [ ] Remove CoinVacuum inside the PlayerSkillManager
- [ ] Make a new PlayerInput for the right mouse button
- [ ] Set the Right mouse button event to be the CoinVacuum

**Comment by Aquarelix** [comment]
Completed with this commit 88813d5
