### ISSUE TITLE
Add AudioManager

### ISSUE THREAD

**Issue by Aquarelix** [Aventero/MagicalMushrooms#28]
## Idea
Make a AudioManager for easily playing sounds.
The sound can set on which audio channel it should run.

## To-Do
- [x] Easily play sounds
- [x] The specific audio channel can be selected when playing sounds
- [x] Sounds can overlap

**Comment by Aquarelix** [comment]
Closed with this Commit: f58dbc6
