### ISSUE TITLE
On activated CoinVacuum all skills should be deactivated

### ISSUE THREAD

**Issue by Aquarelix** [Aventero/MagicalMushrooms#59]
## Idea
If the CoinVacuum is currently activated, then all skills should be deactivated

## To-Do
- [ ] Detect if the coin vacuum is activated
- [ ] Let the SkillManager know if the vacuum is activated
- [ ] Disable all skills if the vacuum is activated
